config/routes.rb
Spree::Core::Engine.routes.prepend do

  namespace :admin do
    resource :yandex_market_settings do
      member do
        match :general
        match :currency
        match :export_files
        match :ware_property
        get :run_export
      end
    end
  end

end

app/controllers/admin/yandex_market_settings_controller.rb
# -*- coding: utf-8 -*-
class Admin::YandexMarketSettingsController < Admin::BaseController  
  before_filter :get_config
  
  def show
    @taxons =  Taxon.roots
  end
  
  def general
    @taxons =  Taxon.roots
  end
  
  def currency
  end
  
  def ware_property
    @properties = Property.all
  end
  
  def export_files
    directory = File.join(Rails.root, 'public', 'yandex_market', '**', '*')
    # нельзя вызывать стат, не удостоверившись в наличии файла!!111
    @export_files =  Dir[directory].map {|x| [File.basename(x), (File.file?(x) ? File.mtime(x) : 0)] }.
      sort{|x,y| y.last <=> x.last }
    e = @export_files.find {|x| x.first == "yandex_market.xml" }
    @export_files.reject! {|x| x.first == "yandex_market.xml" }
    @export_files.unshift(e) unless e.blank?
  end
  
  def run_export
    command = %{cd #{Rails.root} && RAILS_ENV=#{Rails.env} rake spree_yandex_market:generate_ym &}
    logger.info "[ yandex market ] Запуск формирование файла экспорта из блока администрирования "
    logger.info "[ yandex market ] команда - #{command} "
    system command
    flash[:notice] = "Обновите страницу через несколько минут."
    redirect_to export_files_admin_yandex_market_settings_url
  end
  
  def update
    @config.attributes = params[:preferences]
    @config.save!
    
    respond_to do |format|
      format.html {
        redirect_to admin_yandex_market_settings_path
      }
    end
  end

  private

  def get_config
    @config = Spree::YandexMarket::Config.instance
  end
end

app/controllers/spree/admin/yandex_market_settings_controller.rb
# -*- coding: utf-8 -*-
class Spree::Admin::YandexMarketSettingsController < Spree::Admin::BaseController  
  before_filter :get_config
  
  def show
    @taxons =  Spree::Taxon.roots
  end
  
  def general
    @taxons =  Spree::Taxon.roots
  end
  
  def currency
  end
  
  def ware_property
    @properties = Spree::Property.all
  end
  
  def export_files
    directory = File.join(Rails.root, 'public', 'yandex_market', '**', '*')
    # нельзя вызывать стат, не удостоверившись в наличии файла!!111
    @export_files =  Dir[directory].map {|x| [File.basename(x), (File.file?(x) ? File.mtime(x) : 0)] }.
      sort{|x,y| y.last <=> x.last }
    e = @export_files.find {|x| x.first == "yandex_market.xml" }
    @export_files.reject! {|x| x.first == "yandex_market.xml" }
    @export_files.unshift(e) unless e.blank?
  end
  
  def run_export
    command = %{cd #{Rails.root} && RAILS_ENV=#{Rails.env} rake spree_yandex_market:generate_ym &}
    logger.info "[ yandex market ] Запуск формирование файла экспорта из блока администрирования "
    logger.info "[ yandex market ] команда - #{command} "
    system command
    flash[:notice] = "Обновите страницу через несколько минут."
    redirect_to export_files_admin_yandex_market_settings_url
  end
  
  def update   
    @config.set(params[:preferences])
    
    respond_to do |format|
      format.html {
        redirect_to admin_yandex_market_settings_path
      }
    end
  end

  private

  def get_config
    @config = Spree::YandexMarket::Config
  end
end

app/views/spree/admin/yandex_market_settings/currency.html.erb
<%= render :partial => 'spree/admin/yandex_market_settings/shared/configuration_menu' %>
<%= content_tag :h3, t('configure_yandex_market.list_currency'), :class => "name" %>
<%= form_tag(admin_yandex_market_settings_path, :method => :put) do %>
<label for="preferences_preferred_currency">
  <%= t('configure_yandex_market.currency') %>
  <%= text_field_tag('preferences[currency]', @config.preferred_currency, :size => 50) %>
</label>
<br class="clear" />
<br class="clear" />
<div>
Валюты задються в  строке разделенные ';', праметры курса валюты разделяються ':'.
Первая задаеться основная валюта магазина и курс должен равен 1.
Параметры:
<ol>
  <li>Код валюты</li>
  <li>Курс</li>
  <li>Процент курса</li>
</ol>
Пример:
<div>
  <span>RUR:1;USD:CBRF:3;EUR:CBRF:0.2;</span>
  <div>Задано три валюты: RUR - основная, USD - курс CBRF + 3%, EUR - курс CBRF + 0.2%</div> 
</div>
<span>Параметр курс может иметь следующие значения: CBRF, NBU, NBK и CB.</span>
  <ul>
    <li>CBRF - курс по Центральному банку РФ.</li>
    <li>NBU - курс по Национальному банку Украины.</li>
    <li>NBK - курс по Национальному банку Казахстана.</li>
    <li>СВ - курс по банку той страны, к которой относится интернет-магазин по Своему региону, указанному в Партнерском интерфейсе Яндекс.Маркета.</li>
  </ul>
  <div class="warning">
    Внимание!  При слишком значительном (больше 30%) отличии значения курса валюты от курса ЦБ РФ или НБУ информационные материалы считаются невалидными.
  </div>
</div>
<p class="form-buttons">
  <%= button t('update') %> 
  <%= t("or") %> <%= link_to t("cancel"), admin_yandex_market_settings_url %>
</p>
<% end %>

app/views/spree/admin/yandex_market_settings/export_files.html.erb
<%= render :partial => 'spree/admin/yandex_market_settings/shared/configuration_menu' %>
<div class='toolbar'>
  <ul class='actions'>
    <li id="new_ot_link">
      <%= link_to t('configure_yandex_market.run_generate_file'), run_export_admin_yandex_market_settings_path %>
      
    </li>
  </ul>
  <br class='clear' />
</div>
<div id="run_generate_export"></div>
<%= content_tag :h3, t('configure_yandex_market.export_files'), :class => "name" %>
<table class="index">
  <tr>
    <th><%= t('configure_yandex_market.name') %></th>
    <th><%= t('configure_yandex_market.date') %></th>
    <th>&nbsp;</th>
  </tr>
   <% @export_files && @export_files.each do |ef| -%>
  <tr>
    <td><%= ef.first %></td>
    <td><%= ef.last %></td>
    <td class="actions"><%= link_to t("configure_yandex_market.download"), url_for("/yandex_market/#{ef.first}") %> </td>
  </tr>
   <% end -%>
</table>

app/views/spree/admin/yandex_market_settings/general.html.erb
<%= render :partial => 'spree/admin/yandex_market_settings/shared/configuration_menu' %>
<%= content_tag :h3, t('configure_yandex_market.general'), :class => "name" %>
<%= form_tag(admin_yandex_market_settings_path, :method => :put) do %>
<fieldset>
  <label for="preferences_short_name">
    <%= t('configure_yandex_market.short_name') %>
    <br class="clear" />   
    <%= text_field_tag "preferences[short_name]", @config.preferred_short_name, :maxlength => 20 %>
  </label>
  <br class="clear" />
  <label for="preferences_full_name">
    <%= t('configure_yandex_market.full_name') %>
    <br class="clear" />
    <%= text_field_tag "preferences[full_name]", @config.preferred_full_name, :size => 50 %>
  </label>
  <br class="clear" />
  <label for="preferences_url">
    <%= t('configure_yandex_market.url') %>
    <br class="clear" />
    <%= text_field_tag "preferences[url]", @config.preferred_url, :size => 50 %>
  </label>    
</fieldset>

<fieldset>
  <legend><span><%= t('configure_yandex_market.what_wares_export') %></span></legend>
  <ol>
    <li>
      <label for="preferences_wares_active">
        <%= radio_button_tag 'preferences[wares]', 'active', @config.preferred_wares == "active" %>
        <%= t('configure_yandex_market.all_active_wares') %>
      </label>
    </li>
    
    <li>
      <label for="preferences_wares_on_hand">
        <%= radio_button_tag 'preferences[wares]', 'on_hand', @config.preferred_wares == "on_hand" %>
        <%= t('configure_yandex_market.on_hand_wares') %>
      </label>
    </li>
    
  </ol>
</fieldset>
<fieldset>
  <legend><span><%= t('configure_yandex_market.local_delivery_cost') %></span></legend>
  <%= text_field_tag "preferences[local_delivery_cost]", @config.preferred_local_delivery_cost %>
</fieldset>  
<fieldset>
  <legend><span><%= t('configure_yandex_market.sales_notes') %></span></legend>
  <%= text_field_tag "preferences[sales_notes]", @config.preferred_sales_notes %>
</fieldset>  
<fieldset>
  <legend><span><%= t('configure_yandex_market.only_backorder') %></span></legend>
  <%= hidden_field_tag "preferences[only_backorder]", 0 %>
  <%= check_box_tag "preferences[only_backorder]", 1, @config.preferred_only_backorder %>
</fieldset>

<fieldset>
  <legend><span><%= t('configure_yandex_market.without_order_form') %></span></legend>
  <%= hidden_field_tag "preferences[without_order_form]", 0 %>
  <%= check_box_tag "preferences[without_order_form]", 1, @config.preferred_without_order_form %>
</fieldset>

<p class="form-buttons">
  <%= button t('update') %> 
  <%= t("or") %> <%= link_to t("cancel"), admin_yandex_market_settings_url %>
</p>
<% end %>

app/views/spree/admin/yandex_market_settings/show.html.erb
<%= render :partial => 'spree/admin/yandex_market_settings/shared/configuration_menu' %>
<table>
  <tr>
    <th scope="row"><%= t 'configure_yandex_market.short_name_small' %>:</th> 
    <td colspan=2><%= @config.preferred_short_name %></td>
  </tr>
  <tr>
    <th scope="row"><%= t 'configure_yandex_market.full_name_small' %>:</th> 
    <td colspan=2><%= @config.preferred_full_name %></td>
  </tr>
  <tr>
    <th scope="row"><%= t 'configure_yandex_market.url' %>:</th> 
    <td colspan=2><%= @config.preferred_url %></td>
  </tr>      
  <tr>
    <th scope="row"><%= t 'configure_yandex_market.currency' %>:</th> 
    <td colspan=2><%= @config.preferred_currency %></td>
  </tr>
  <tr>
    <th scope="row"><%= t 'configure_yandex_market.export_wares' %>:</th> 
    <td colspan=2><%= t("yandex_market_wares_#{@config.preferred_wares}") %></td>
  </tr>
  <tr>
    <th scope="row"><%= t 'configure_yandex_market.local_delivery_cost' %>:</th> 
    <td colspan=2><%= @config.preferred_local_delivery_cost %></td>
  </tr>
  <tr>
    <th scope="row"><%= t 'configure_yandex_market.sales_notes' %>:</th>
    <td colspan=2><%= @config.preferred_sales_notes %></td>
  </tr>
  <tr>
    <th scope="row"><%= t 'configure_yandex_market.only_backorder' %>:</th>
    <td colspan=2><%= @config.preferred_only_backorder %></td>
  </tr>
  <tr>
    <th scope="row"><%= t 'configure_yandex_market.without_order_form' %>:</th>
    <td colspan=2><%= @config.preferred_without_order_form %></td>
  </tr>

  <tr>
    <th scope="row"><%= t 'configure_yandex_market.export_file' %>:</th> 
    <td>
      <%= link_to(url_for("http://#{@config.preferred_url.sub(%r[^http://],'').sub(%r[/$],'')}/#{'/yandex_market/yandex_market.xml'.sub(%r[^/],'')}"),  url_for("/yandex_market/yandex_market.xml")) if @config.preferred_url %>
    </td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <th scope="row"><%= t 'configure_yandex_market.ware_property' %>:</th> 
    <td colspan=2>
      <ul>
        <% ["type_prefix", "vendor", "model", "vendor_code",
           "country_of_manufacturer", "manufacturer_warranty", "wares_type" ].each do |property| -%>
        <li>
          <%= t("configure_yandex_market.#{property}") %>: <%=  @config.send("preferred_#{property}".to_sym) %>
        </li>
        <% end -%>
          
      </ul>
    </td>

  </tr>
</table>

app/views/spree/admin/yandex_market_settings/ware_property.html.erb
<%= render :partial => 'spree/admin/yandex_market_settings/shared/configuration_menu' %>

<%= content_tag :h3, t('configure_yandex_market.ware_property'), :class => "name" %>

<%= form_tag(admin_yandex_market_settings_path, :method => :put) do -%>
<fieldset>
  <legend><span><%= t('configure_yandex_market.field_for') %></span></legend>
  <label><%= radio_button_tag 'wares_type', 'simple', true %> Основные</label>
  <label><%= radio_button_tag 'wares_type', 'book' %> Книги </label>
  <label><%= radio_button_tag 'wares_type', 'music_video' %> Музыка/Видео </label>
  <label><%= radio_button_tag 'wares_type', 'event_ticket' %> Билеты на мероприятия</label>
</fieldset>

<fieldset class="fields" id="simple">
  <legend><span><%= t('configure_yandex_market.basic_property') %></span></legend>
  <table class="index">
    <% ["wares_type", "type_prefix","vendor", "model", "vendor_code",
       "country_of_manufacturer", "manufacturer_warranty" ].each do |property| -%>
    <tr>
      <td><%= t("configure_yandex_market.#{property}") %>:</td>
      <td>
        <%= select_tag("preferences[#{property}]",
            options_for_select(@properties.collect{ |u| ["#{u.presentation} (#{u.name})", u.name] }.unshift([nil, nil]), @config.send("preferred_#{property}".to_sym))) -%>
        </td>
      </tr>
    <% end -%>
  </table>
</fieldset>
<fieldset class="fields" id="book" style="display:none;">
  <legend><span><%= t('configure_yandex_market.book_property') %></span></legend>
  <table class="index">
    <% %w{author publisher series year isbn volume part language binding page_extent performed_by storage format recording_length}.each do |property| -%>
    <tr>
      <td><%= t("configure_yandex_market.#{property}") %>:</td>
      <td>
        <%= select_tag("preferences[#{property}]",
            options_for_select(@properties.collect{ |u| ["#{u.presentation} (#{u.name})", u.name] }.unshift([nil, nil]), @config.send("preferred_#{property}".to_sym))) -%>
        </td>
      </tr>
    <% end -%>
  </table>
</fieldset>
<fieldset class="fields" id="music_video" style="display:none;">
<legend><span><%= t('configure_yandex_market.music_video_property') %></span></legend>
  <table class="index">
    <% %w{ artist title music_video_year media starring director original_name video_country }.each do |property| -%>
    <tr>
      <td><%= t("configure_yandex_market.#{property}") %>:</td>
      <td>
        <%= select_tag("preferences[#{property}]",
            options_for_select(@properties.collect{ |u| ["#{u.presentation} (#{u.name})", u.name] }.unshift([nil, nil]), @config.send("preferred_#{property}".to_sym))) -%>
        </td>
      </tr>
    <% end -%>
  </table>
  
</fieldset>
<fieldset class="fields" id="event_ticket" style="display:none;">
<legend><span><%= t('configure_yandex_market.event_ticket_property') %></span></legend>
  <table class="index">
    <% %w{ place hall hall_url_plan event_date is_premiere is_kids  }.each do |property| -%>
    <tr>
      <td><%= t("configure_yandex_market.#{property}") %>:</td>
      <td>
        <%= select_tag("preferences[#{property}]",
            options_for_select(@properties.collect{ |u| ["#{u.presentation} (#{u.name})", u.name] }.unshift([nil, nil]), @config.send("preferred_#{property}".to_sym))) -%>
        </td>
      </tr>
    <% end -%>
  </table>

</fieldset>

<p class="form-buttons">
  <%= button t('update') %> 
  <%= t("or") %> <%= link_to t("cancel"), admin_yandex_market_settings_url %>
</p>
<% end -%>
<script type="text/javascript" charset="utf-8">
  $(function(){
  $("input[type='radio']").change(function(){
    $("fieldset.fields").hide();
    $("fieldset#"+$(this).val()).show();
    });
  });
</script>