config/routes.rb
Spree::Core::Engine.routes.prepend do

  namespace :admin do
    resource :yandex_market_settings do
      member do
        match :general
        match :currency
        match :export_files
        match :ware_property
        get :run_export
      end
    end
  end

end

app/controllers/admin/yandex_market_settings_controller.rb
# -*- coding: utf-8 -*-
class Admin::YandexMarketSettingsController < Admin::BaseController  
  before_filter :get_config
  
  def show
    @taxons =  Taxon.roots
  end
  
  def general
    @taxons =  Taxon.roots
  end
  
  def currency
  end
  
  def ware_property
    @properties = Property.all
  end
  
  def export_files
    directory = File.join(Rails.root, 'public', 'yandex_market', '**', '*')
    # нельзя вызывать стат, не удостоверившись в наличии файла!!111
    @export_files =  Dir[directory].map {|x| [File.basename(x), (File.file?(x) ? File.mtime(x) : 0)] }.
      sort{|x,y| y.last <=> x.last }
    e = @export_files.find {|x| x.first == "yandex_market.xml" }
    @export_files.reject! {|x| x.first == "yandex_market.xml" }
    @export_files.unshift(e) unless e.blank?
  end
  
  def run_export
    command = %{cd #{Rails.root} && RAILS_ENV=#{Rails.env} rake spree_yandex_market:generate_ym &}
    logger.info "[ yandex market ] Запуск формирование файла экспорта из блока администрирования "
    logger.info "[ yandex market ] команда - #{command} "
    system command
    flash[:notice] = "Обновите страницу через несколько минут."
    redirect_to export_files_admin_yandex_market_settings_url
  end
  
  def update
    @config.attributes = params[:preferences]
    @config.save!
    
    respond_to do |format|
      format.html {
        redirect_to admin_yandex_market_settings_path
      }
    end
  end

  private

  def get_config
    @config = Spree::YandexMarket::Config.instance
  end
end

app/controllers/spree/admin/yandex_market_settings_controller.rb
# -*- coding: utf-8 -*-
class Spree::Admin::YandexMarketSettingsController < Spree::Admin::BaseController  
  before_filter :get_config
  
  def show
    @taxons =  Spree::Taxon.roots
  end
  
  def general
    @taxons =  Spree::Taxon.roots
  end
  
  def currency
  end
  
  def ware_property
    @properties = Spree::Property.all
  end
  
  def export_files
    directory = File.join(Rails.root, 'public', 'yandex_market', '**', '*')
    # нельзя вызывать стат, не удостоверившись в наличии файла!!111
    @export_files =  Dir[directory].map {|x| [File.basename(x), (File.file?(x) ? File.mtime(x) : 0)] }.
      sort{|x,y| y.last <=> x.last }
    e = @export_files.find {|x| x.first == "yandex_market.xml" }
    @export_files.reject! {|x| x.first == "yandex_market.xml" }
    @export_files.unshift(e) unless e.blank?
  end
  
  def run_export
    command = %{cd #{Rails.root} && RAILS_ENV=#{Rails.env} rake spree_yandex_market:generate_ym &}
    logger.info "[ yandex market ] Запуск формирование файла экспорта из блока администрирования "
    logger.info "[ yandex market ] команда - #{command} "
    system command
    flash[:notice] = "Обновите страницу через несколько минут."
    redirect_to export_files_admin_yandex_market_settings_url
  end
  
  def update   
    @config.set(params[:preferences])
    
    respond_to do |format|
      format.html {
        redirect_to admin_yandex_market_settings_path
      }
    end
  end

  private

  def get_config
    @config = Spree::YandexMarket::Config
  end
end

app/views/spree/admin/yandex_market_settings/shared/_configuration_menu.html.erb
<% content_for :sidebar do %>
  <%= content_tag :h5, content_tag(:span, t('configure_yandex_market.title')), :class => "sidebar-title" %>

    <nav class="menu">
      <ul class="sidebar">
        <%= content_tag :li, :class => (params[:action] == "general" ? "active": "")  do -%>
        <%= link_to t("configure_yandex_market.general"), general_admin_yandex_market_settings_path %>
        <% end -%>
        
        <%= content_tag :li, :class => (params[:action] == "currency" ? "active": "")  do -%>
        <%= link_to t("configure_yandex_market.list_currency") , currency_admin_yandex_market_settings_path %>
        <% end -%>
        
        <%= content_tag :li, :class => (params[:action] == "export_files" ? "active": "")  do -%>
        <%= link_to t("configure_yandex_market.export_files"),export_files_admin_yandex_market_settings_path %>
        <% end -%>

        
        <%= content_tag :li, :class => (params[:action] == "ware_property" ? "active": "")  do -%>
        <%= link_to t("configure_yandex_market.ware_property"),ware_property_admin_yandex_market_settings_path %>
        <% end -%>
      </ul>
    </nav>
<% end -%>